%Kayla Haines
%CSC 4630/6630 PC9
%Due Mar 14 2021

global img;
global img_handle;
global startRow;
global startCol;
global moveVal;
global showVal;

%create figure handle
fig_handle = figure;

moveVal = 64;
showVal = 128;
startRow = 1;
startCol = 1;

img = imread('testim.JPG');
img_handle = axes('Parent',fig_handle,...
    'Position', [.25 .4 .5 .5]);
imshow(img(startRow:startRow+128, startCol:startCol+128, :));

%add left, right, up, down buttons
left_handle = uicontrol('Parent',fig_handle,...
    'Style','pushbutton',...
    "String",'left',...
    "Position",[150 0 50 50],...
    'Callback',{'button_callback',1});
right_handle = uicontrol('Parent',fig_handle,...
    'Style','pushbutton',...
    "String",'right',...
    "Position",[250 0 50 50],...
    'Callback',{'button_callback',2});
up_handle = uicontrol('Parent',fig_handle,...
    'Style','pushbutton',...
    "String",'up',...
    "Position",[200 50 50 50],...
    'Callback',{'button_callback',3});
down_handle = uicontrol('Parent',fig_handle,...
    'Style','pushbutton',...
    "String",'down',...
    "Position",[200 0 50 50],...
    'Callback',{'button_callback',4});