
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD CAR CDR CONS DIV INT LET LPAREN MUL RPAREN SEMI SUB VARlstart : lisp SEMIlisp : INTlisp : VARlisp : LPAREN ADD lisp lisp RPARENlisp : LPAREN SUB lisp lisp RPARENlisp : LPAREN MUL lisp lisp RPARENlisp : LPAREN DIV lisp lisp RPARENlisp : LPAREN CAR list RPARENlisp : LPAREN LET LPAREN keyval RPAREN lisp RPARENlisp : listkeyval : LPAREN VAR lisp RPARENkeyval : LPAREN VAR lisp RPAREN keyvallist : LPAREN CDR list RPARENlist : LPAREN CONS lisp list RPARENlist : LPAREN seq RPARENseq : lispseq : lisp seq'
    
_lr_action_items = {'INT':([0,3,4,5,6,8,9,10,11,12,16,18,20,21,22,23,28,33,36,38,39,40,41,42,43,44,48,],[3,-2,-3,3,-10,3,3,3,3,3,3,3,3,3,3,3,-15,-8,-13,-4,-5,-6,-7,3,3,-14,-9,]),'VAR':([0,3,4,5,6,8,9,10,11,12,16,18,20,21,22,23,28,33,34,36,38,39,40,41,42,43,44,48,],[4,-2,-3,4,-10,4,4,4,4,4,4,4,4,4,4,4,-15,-8,42,-13,-4,-5,-6,-7,4,4,-14,-9,]),'LPAREN':([0,3,4,5,6,8,9,10,11,12,13,14,15,16,18,20,21,22,23,25,27,28,33,36,38,39,40,41,42,43,44,47,48,],[5,-2,-3,5,-10,5,5,5,5,5,23,25,23,5,5,5,5,5,5,34,23,-15,-8,-13,-4,-5,-6,-7,5,5,-14,34,-9,]),'$end':([1,7,],[0,-1,]),'SEMI':([2,3,4,6,28,33,36,38,39,40,41,44,48,],[7,-2,-3,-10,-15,-8,-13,-4,-5,-6,-7,-14,-9,]),'RPAREN':([3,4,6,9,17,19,24,26,28,29,30,31,32,33,35,36,37,38,39,40,41,44,45,46,47,48,49,],[-2,-3,-10,-16,28,-17,33,36,-15,38,39,40,41,-8,43,-13,44,-4,-5,-6,-7,-14,47,48,-11,-9,-12,]),'ADD':([5,],[8,]),'SUB':([5,],[10,]),'MUL':([5,],[11,]),'DIV':([5,],[12,]),'CAR':([5,],[13,]),'LET':([5,],[14,]),'CDR':([5,23,],[15,15,]),'CONS':([5,23,],[16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lstart':([0,],[1,]),'lisp':([0,5,8,9,10,11,12,16,18,20,21,22,23,42,43,],[2,9,18,9,20,21,22,27,29,30,31,32,9,45,46,]),'list':([0,5,8,9,10,11,12,13,15,16,18,20,21,22,23,27,42,43,],[6,6,6,6,6,6,6,24,26,6,6,6,6,6,6,37,6,6,]),'seq':([5,9,23,],[17,19,17,]),'keyval':([25,47,],[35,49,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lstart","S'",1,None,None,None),
  ('lstart -> lisp SEMI','lstart',2,'p_lstart','LispParser.py',6),
  ('lisp -> INT','lisp',1,'p_lisp_1','LispParser.py',9),
  ('lisp -> VAR','lisp',1,'p_lisp_2','LispParser.py',13),
  ('lisp -> LPAREN ADD lisp lisp RPAREN','lisp',5,'p_lisp_3','LispParser.py',17),
  ('lisp -> LPAREN SUB lisp lisp RPAREN','lisp',5,'p_lisp_4','LispParser.py',21),
  ('lisp -> LPAREN MUL lisp lisp RPAREN','lisp',5,'p_lisp_5','LispParser.py',25),
  ('lisp -> LPAREN DIV lisp lisp RPAREN','lisp',5,'p_lisp_6','LispParser.py',29),
  ('lisp -> LPAREN CAR list RPAREN','lisp',4,'p_lisp_7','LispParser.py',33),
  ('lisp -> LPAREN LET LPAREN keyval RPAREN lisp RPAREN','lisp',7,'p_lisp_8','LispParser.py',45),
  ('lisp -> list','lisp',1,'p_lisp_9','LispParser.py',49),
  ('keyval -> LPAREN VAR lisp RPAREN','keyval',4,'p_keyval_1','LispParser.py',54),
  ('keyval -> LPAREN VAR lisp RPAREN keyval','keyval',5,'p_keyval_2','LispParser.py',58),
  ('list -> LPAREN CDR list RPAREN','list',4,'p_list_1','LispParser.py',64),
  ('list -> LPAREN CONS lisp list RPAREN','list',5,'p_list_2','LispParser.py',69),
  ('list -> LPAREN seq RPAREN','list',3,'p_list_3','LispParser.py',73),
  ('seq -> lisp','seq',1,'p_seq_1','LispParser.py',78),
  ('seq -> lisp seq','seq',2,'p_seq_2','LispParser.py',82),
]
